DEFINE OUTPUT PARAMETER opiForEachCount AS INT64 NO-UNDO.
DEFINE OUTPUT PARAMETER opiForEachMs AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER opiPreselectCount AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER opiOpenQueryMs AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER opiNumResultsMs AS INTEGER NO-UNDO.

DEFINE QUERY qBenchCustomer FOR Customer
    FIELDS(CustNum)
    SCROLLING.

ETIME(TRUE).
FOR EACH Customer NO-LOCK:
    ASSIGN opiForEachCount = opiForEachCount + 1.
END.
ASSIGN opiForEachMs = ETIME.

ETIME(TRUE).
OPEN QUERY qBenchCustomer PRESELECT EACH Customer NO-LOCK.
ASSIGN opiOpenQueryMs = ETIME.

ETIME(TRUE).
ASSIGN opiPreselectCount = NUM-RESULTS("qBenchCustomer").
ASSIGN opiNumResultsMs = ETIME.

CLOSE QUERY qBenchCustomer.
