DEFINE VARIABLE cJobId AS CHARACTER NO-UNDO.
DEFINE VARIABLE lcRequest AS LONGCHAR NO-UNDO.
DEFINE VARIABLE lcPlan AS LONGCHAR NO-UNDO.

INPUT FROM VALUE("D:\opencode\motor-progress\temp\last_async_job.txt").
IMPORT UNFORMATTED cJobId.
INPUT CLOSE.

FIND FIRST SursumQueryJob NO-LOCK
    WHERE SursumQueryJob.jobId = cJobId
    NO-ERROR.

IF NOT AVAILABLE SursumQueryJob THEN DO:
    MESSAGE "DEBUG_JOB_FOUND=no".
    QUIT.
END.

COPY-LOB FROM SursumQueryJob.requestJson TO lcRequest NO-ERROR.
COPY-LOB FROM SursumQueryJob.planJson TO lcPlan NO-ERROR.

MESSAGE "DEBUG_JOB_FOUND=yes".
MESSAGE "DEBUG_JOB_STATUS=" + SursumQueryJob.jobStatus.
MESSAGE "DEBUG_REQUEST_LENGTH=" + STRING(LENGTH(lcRequest)).
MESSAGE "DEBUG_PLAN_LENGTH=" + STRING(LENGTH(lcPlan)).
MESSAGE "DEBUG_REQUEST_PREFIX=" + SUBSTRING(lcRequest, 1, MINIMUM(80, LENGTH(lcRequest))).

QUIT.
