/*
Consulta via APSV/PASOE o status do ultimo job async.
*/

DEFINE VARIABLE hServer AS HANDLE NO-UNDO.
DEFINE VARIABLE lOk AS LOGICAL NO-UNDO.
DEFINE VARIABLE lcResult AS LONGCHAR NO-UNDO.
DEFINE VARIABLE cJobId AS CHARACTER NO-UNDO.

INPUT FROM VALUE("D:\opencode\motor-progress\temp\last_async_job.txt").
IMPORT UNFORMATTED cJobId.
INPUT CLOSE.

CREATE SERVER hServer.
ASSIGN lOk = hServer:CONNECT("-URL http://localhost:8890/apsv") NO-ERROR.

IF ERROR-STATUS:ERROR OR NOT lOk THEN DO:
    MESSAGE "PASOE_STATUS_CONNECT_SUCCESS=no".
    MESSAGE ERROR-STATUS:GET-MESSAGE(1).
    DELETE OBJECT hServer NO-ERROR.
    QUIT.
END.

RUN VALUE("GetDynamicQueryJobStatusPasoe.p") ON SERVER hServer (INPUT cJobId, OUTPUT lcResult) NO-ERROR.

IF ERROR-STATUS:ERROR THEN DO:
    MESSAGE "PASOE_STATUS_SUCCESS=no".
    MESSAGE ERROR-STATUS:GET-MESSAGE(1).
END.
ELSE DO:
    MESSAGE "PASOE_STATUS_CONNECT_SUCCESS=yes".
    MESSAGE "PASOE_STATUS_SUCCESS=yes".
    MESSAGE "PASOE_STATUS_RESULT=" + STRING(lcResult).
END.

hServer:DISCONNECT() NO-ERROR.
DELETE OBJECT hServer NO-ERROR.

QUIT.
