/*
Chama o worker remoto no PASOE via APSV.
*/

DEFINE VARIABLE hServer AS HANDLE NO-UNDO.
DEFINE VARIABLE lOk AS LOGICAL NO-UNDO.
DEFINE VARIABLE lcResult AS LONGCHAR NO-UNDO.

CREATE SERVER hServer.

ASSIGN lOk = hServer:CONNECT("-URL http://localhost:8890/apsv") NO-ERROR.

IF ERROR-STATUS:ERROR OR NOT lOk THEN DO:
    MESSAGE "PASOE_CONNECT_SUCCESS=no".
    MESSAGE ERROR-STATUS:GET-MESSAGE(1).
    DELETE OBJECT hServer NO-ERROR.
    QUIT.
END.

RUN VALUE("DrainDynamicQueryPasoe.p") ON SERVER hServer (OUTPUT lcResult) NO-ERROR.

IF ERROR-STATUS:ERROR THEN DO:
    MESSAGE "PASOE_WORKER_SUCCESS=no".
    MESSAGE ERROR-STATUS:GET-MESSAGE(1).
END.
ELSE DO:
    MESSAGE "PASOE_CONNECT_SUCCESS=yes".
    MESSAGE "PASOE_WORKER_SUCCESS=yes".
    MESSAGE "PASOE_WORKER_RESULT=" + STRING(lcResult).
END.

hServer:DISCONNECT() NO-ERROR.
DELETE OBJECT hServer NO-ERROR.

QUIT.
