/* Aliases para base teste Datasul.
   Mantem o arquivo separado da producao para uso pelo resolvedor remoto
   e pelo catalogo de metadados do motor Progress. */

CREATE ALIAS mgcad  FOR DATABASE ems2cad NO-ERROR.
CREATE ALIAS mgadm  FOR DATABASE ems2cad NO-ERROR.
CREATE ALIAS mginv  FOR DATABASE ems2cad NO-ERROR.
CREATE ALIAS mgfro  FOR DATABASE ems2cad NO-ERROR.
CREATE ALIAS mguni  FOR DATABASE ems2cad NO-ERROR.

CREATE ALIAS ems2ima FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgind   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgdis   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgfis   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgcld   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgcex   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgmfg   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgmnt   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgmrp   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgscm   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgdbr   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgrac   FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS emsgra  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS emsdca  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS ems2oe  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS mgsop   FOR DATABASE ems2med NO-ERROR.

CREATE ALIAS movadm  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movdis  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movfis  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movind  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movmfg  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movmnt  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS wmovdis FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movfro  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movdbr  FOR DATABASE ems2med NO-ERROR.
CREATE ALIAS movrac  FOR DATABASE ems2med NO-ERROR.

CREATE ALIAS movfin FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsbas FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsedi FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsfin FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsuni FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsven FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsnam FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emscad FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsmov FOR DATABASE ems5 NO-ERROR.

CREATE ALIAS dthrgst FOR DATABASE hcm NO-ERROR.
CREATE ALIAS dthrpmg FOR DATABASE hcm NO-ERROR.
CREATE ALIAS dthrpyc FOR DATABASE hcm NO-ERROR.
CREATE ALIAS dthrtma FOR DATABASE hcm NO-ERROR.
