#
b D:\opencode\motor-progress\db\
#
d "Schema Area":6,32;1 D:\opencode\motor-progress\db\
#
d "Employee":7,32;1 D:\opencode\motor-progress\db\ f 320
d "Employee":7,32;1 D:\opencode\motor-progress\db\
#
d "Inventory":8,32;1 D:\opencode\motor-progress\db\ f 640
d "Inventory":8,32;1 D:\opencode\motor-progress\db\
#
d "Cust_Data":9,32;1 D:\opencode\motor-progress\db\ f 320
d "Cust_Data":9,32;1 D:\opencode\motor-progress\db\
#
d "Cust_Index":10,32;1 D:\opencode\motor-progress\db\ f 320
d "Cust_Index":10,32;1 D:\opencode\motor-progress\db\
#
d "Order":11,32;1 D:\opencode\motor-progress\db\ f 1280
d "Order":11,32;1 D:\opencode\motor-progress\db\
#
d "Misc":12,32;1 D:\opencode\motor-progress\db\ f 320
d "Misc":12,32;1 D:\opencode\motor-progress\db\
