create ALIAS mgcad		for DATABASE ems2cad    no-error.
create alias mgadm		for database ems2cad    no-error.
create alias mginv		for database ems2cad    no-error.
create alias mgfro		for database ems2cad    no-error.
create alias mguni		for database ems2cad    no-error.
create ALIAS ems2ima	for database ems2med    no-error.
create alias mgind		for database ems2med    no-error.
create alias mgdis		for database ems2med    no-error.
create alias mgfis		for database ems2med    no-error.
create alias mgcld		for database ems2med    no-error.
create alias mgcex		for database ems2med    no-error.
create alias mgmfg		for database ems2med    no-error.
create alias mgmnt		for database ems2med    no-error.
create alias mgmrp		for database ems2med    no-error.
create alias mgscm		for database ems2med    no-error.
create alias mgdbr		for database ems2med    no-error.
create alias emsgra		for database ems2med    no-error.
create alias emsdca		for database ems2med    no-error.
create alias ems2oe		for database ems2med    no-error.
create alias mgsop		for database ems2med    no-error.
create alias movadm		for database ems2med    no-error.
create alias movdis		for database ems2med    no-error.
create alias movfis		for database ems2med    no-error.
create alias movind		for database ems2med    no-error.
create alias movmfg		for database ems2med    no-error.
create alias movmnt		for database ems2med    no-error.
create alias wmovdis	for database ems2med    no-error.
create alias movfro		for database ems2med    no-error.
create alias movdbr		for database ems2med    no-error.
create alias dthrgst	for database hcm	  no-error.
create alias dthrpmg	for database hcm	  no-error.
create alias dthrpyc	for database hcm	  no-error.
create alias dthrtma	for database hcm	  no-error.
create alias movfin		for database ems5	  no-error.     
create alias emsbas		for database ems5	  no-error.
create alias emsedi		for database ems5	  no-error.
create alias emsfin		for database ems5	  no-error.
create alias emsuni		for database ems5	  no-error.     
create alias emsven		for database ems5	  no-error.     
create alias emsnam		for database ems5	  no-error.
create alias emscad		for database ems5	  no-error.     
create alias emsmov		for database ems5	  no-error.
