FUNCTION getChar RETURNS CHARACTER (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER, INPUT pcDefault AS CHARACTER) FORWARD.
FUNCTION getInt RETURNS INTEGER (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER, INPUT piDefault AS INTEGER) FORWARD.
FUNCTION getInt64 RETURNS INT64 (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER, INPUT piDefault AS INT64) FORWARD.
FUNCTION getDec RETURNS DECIMAL (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER, INPUT pdDefault AS DECIMAL) FORWARD.
FUNCTION getLog RETURNS LOGICAL (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER, INPUT plDefault AS LOGICAL) FORWARD.
FUNCTION getObject RETURNS JsonObject (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER) FORWARD.
FUNCTION getArray RETURNS JsonArray (INPUT poObj AS JsonObject, INPUT pcName AS CHARACTER) FORWARD.
FUNCTION listFromArray RETURNS CHARACTER (INPUT poArray AS JsonArray) FORWARD.
