FUNCTION decimalJson RETURNS DECIMAL (INPUT pcValor AS CHARACTER) FORWARD.
FUNCTION intFromChar RETURNS INTEGER (INPUT pcValor AS CHARACTER, INPUT piDefault AS INTEGER) FORWARD.
FUNCTION logFromChar RETURNS LOGICAL (INPUT pcValor AS CHARACTER, INPUT plDefault AS LOGICAL) FORWARD.
FUNCTION decFromChar RETURNS DECIMAL (INPUT pcValor AS CHARACTER, INPUT pdDefault AS DECIMAL) FORWARD.
